runtime: php81

handlers:
  - url: /css
    static_dir: css
  - url: /images
    static_dir: images
  - url: /favicon.ico
    static_files: images/favicons/favicon.ico
    upload: images/favicons/favicon.ico
  - url: /lp-1
    static_files: lp-1/index.html
    upload: lp-1/index.html
    require_matching_file: true
  - url: /lp-1/(.*)
    static_files: lp-1/\1
    upload: lp-1/.*
  - url: /.*
    static_files: index.html
    upload: index.html
  - url: .*
    script: auto