runtime: php81
env: standard
instance_class: F1

handlers:
  - url: /css/(.*)
    static_files: css/\1
    upload: css/.*
  - url: /images/(.*)
    static_files: images/\1
    upload: images/.*
  - url: /favicon.ico
    static_files: images/favicons/favicon.ico
    upload: images/favicons/favicon.ico
  - url: /lp-1/assets/(.*)
    static_files: lp-1/assets/\1
    upload: lp-1/assets/.*
  - url: /lp-1
    static_files: lp-1/index.html
    upload: lp-1/index.html
  - url: /.*
    static_files: index.html
    upload: index.html
  - url: .*
    script: auto

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: 167598555247-compute@developer.gserviceaccount.com